spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ugc_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: your_password
    driver-class-name: com.mysql.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        connection:
          characterEncoding: utf8
          useUnicode: true
          charSet: UTF-8

openai:
  api-key: sk-QjwicNbZGl3vItLH9164DaE7Ed46434a97Da8aB00bCcBd99
  base-url: https://vip.apiyi.com/v1

server:
  port: 8080 